"use strict";(self.webpackChunkzio_site=self.webpackChunkzio_site||[]).push([[52162],{15680:(e,r,n)=>{n.d(r,{xA:()=>p,yg:()=>h});var t=n(96540);function a(e,r,n){return r in e?Object.defineProperty(e,r,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[r]=n,e}function o(e,r){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var t=Object.getOwnPropertySymbols(e);r&&(t=t.filter((function(r){return Object.getOwnPropertyDescriptor(e,r).enumerable}))),n.push.apply(n,t)}return n}function l(e){for(var r=1;r<arguments.length;r++){var n=null!=arguments[r]?arguments[r]:{};r%2?o(Object(n),!0).forEach((function(r){a(e,r,n[r])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(r){Object.defineProperty(e,r,Object.getOwnPropertyDescriptor(n,r))}))}return e}function i(e,r){if(null==e)return{};var n,t,a=function(e,r){if(null==e)return{};var n,t,a={},o=Object.keys(e);for(t=0;t<o.length;t++)n=o[t],r.indexOf(n)>=0||(a[n]=e[n]);return a}(e,r);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(t=0;t<o.length;t++)n=o[t],r.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var s=t.createContext({}),c=function(e){var r=t.useContext(s),n=r;return e&&(n="function"==typeof e?e(r):l(l({},r),e)),n},p=function(e){var r=c(e.components);return t.createElement(s.Provider,{value:r},e.children)},d="mdxType",u={inlineCode:"code",wrapper:function(e){var r=e.children;return t.createElement(t.Fragment,{},r)}},y=t.forwardRef((function(e,r){var n=e.components,a=e.mdxType,o=e.originalType,s=e.parentName,p=i(e,["components","mdxType","originalType","parentName"]),d=c(n),y=a,h=d["".concat(s,".").concat(y)]||d[y]||u[y]||o;return n?t.createElement(h,l(l({ref:r},p),{},{components:n})):t.createElement(h,l({ref:r},p))}));function h(e,r){var n=arguments,a=r&&r.mdxType;if("string"==typeof e||a){var o=n.length,l=new Array(o);l[0]=y;var i={};for(var s in r)hasOwnProperty.call(r,s)&&(i[s]=r[s]);i.originalType=e,i[d]="string"==typeof e?e:a,l[1]=i;for(var c=2;c<o;c++)l[c]=n[c];return t.createElement.apply(null,l)}return t.createElement.apply(null,n)}y.displayName="MDXCreateElement"},47139:(e,r,n)=>{n.r(r),n.d(r,{assets:()=>s,contentTitle:()=>l,default:()=>u,frontMatter:()=>o,metadata:()=>i,toc:()=>c});var t=n(58168),a=(n(96540),n(15680));const o={id:"handling-errors",title:"Handling Errors"},l=void 0,i={unversionedId:"overview/handling-errors",id:"overview/handling-errors",title:"Handling Errors",description:"ZIO effects may fail due to foreseen or unforeseen problems. In order to help you build robust applications, ZIO tracks foreseen errors at compile-time, letting you know which effects can fail, and how they can fail. For non-recoverable problems, ZIO gives you full insight into the cause of failures (even if unexpected or catastrophic), preserving all information and automatically logging unhandled errors.",source:"@site/docs/overview/handling-errors.md",sourceDirName:"overview",slug:"/overview/handling-errors",permalink:"/overview/handling-errors",draft:!1,editUrl:"https://github.com/zio/zio/edit/series/2.x/docs/overview/handling-errors.md",tags:[],version:"current",frontMatter:{id:"handling-errors",title:"Handling Errors"},sidebar:"overview_sidebar",previous:{title:"Basic Operations",permalink:"/overview/basic-operations"},next:{title:"Handling Resources",permalink:"/overview/handling-resources"}},s={},c=[{value:"Either",id:"either",level:2},{value:"Catching All Errors",id:"catching-all-errors",level:2},{value:"Catching Some Errors",id:"catching-some-errors",level:2},{value:"Fallback",id:"fallback",level:2},{value:"Folding",id:"folding",level:2},{value:"Retrying",id:"retrying",level:2},{value:"Next Steps",id:"next-steps",level:2}],p={toc:c},d="wrapper";function u(e){let{components:r,...n}=e;return(0,a.yg)(d,(0,t.A)({},p,n,{components:r,mdxType:"MDXLayout"}),(0,a.yg)("p",null,"ZIO effects may fail due to foreseen or unforeseen problems. In order to help you build robust applications, ZIO tracks foreseen errors at compile-time, letting you know which effects can fail, and how they can fail. For non-recoverable problems, ZIO gives you full insight into the cause of failures (even if unexpected or catastrophic), preserving all information and automatically logging unhandled errors."),(0,a.yg)("p",null,"In this section, you will learn about some of the tools ZIO gives you to build applications with robust error management."),(0,a.yg)("h2",{id:"either"},"Either"),(0,a.yg)("p",null,"With the ",(0,a.yg)("inlineCode",{parentName:"p"},"ZIO#either")," method, you can transform an effect that fails into an infallible effect that places both failure and success into Scala's ",(0,a.yg)("inlineCode",{parentName:"p"},"Either")," type. This brings the error from the error channel to the success channel, which is useful because many ZIO operators work on the success channel, not the error channel."),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val zeither: ZIO[Any, Nothing, Either[String, Nothing]] = \n  ZIO.fail("Uh oh!").either\n')),(0,a.yg)("h2",{id:"catching-all-errors"},"Catching All Errors"),(0,a.yg)("p",null,"If you want to catch and recover from all types of recoverable errors and effectfully attempt recovery, then you can use the ",(0,a.yg)("inlineCode",{parentName:"p"},"catchAll")," method, which lets you specify an error handler that returns the effect to execute in the event of an error:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val z: ZIO[Any, IOException, Array[Byte]] = \n  openFile("primary.json").catchAll { error => \n    for {\n      _    <- ZIO.logErrorCause("Could not open primary file", Cause.fail(error))\n      file <- openFile("backup.json")\n    } yield file \n  }\n')),(0,a.yg)("p",null,"In the error handler passed to ",(0,a.yg)("inlineCode",{parentName:"p"},"catchAll"),", you may return an effect with a ",(0,a.yg)("em",{parentName:"p"},"different")," error type (perhaps ",(0,a.yg)("inlineCode",{parentName:"p"},"Nothing"),", if the error handler cannot fail), which is then reflected in the type of effect returned by ",(0,a.yg)("inlineCode",{parentName:"p"},"catchAll"),"."),(0,a.yg)("h2",{id:"catching-some-errors"},"Catching Some Errors"),(0,a.yg)("p",null,"If you want to catch and recover from only some types of recoverable errors and effectfully attempt recovery, then you can use the ",(0,a.yg)("inlineCode",{parentName:"p"},"catchSome")," method:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val data: ZIO[Any, IOException, Array[Byte]] = \n  openFile("primary.data").catchSome {\n    case _ : FileNotFoundException => \n      openFile("backup.data")\n  }\n')),(0,a.yg)("p",null,"Unlike ",(0,a.yg)("inlineCode",{parentName:"p"},"catchAll"),", ",(0,a.yg)("inlineCode",{parentName:"p"},"catchSome")," cannot reduce or eliminate the error type, although it can widen the error type to a broader class of errors."),(0,a.yg)("h2",{id:"fallback"},"Fallback"),(0,a.yg)("p",null,"You can try one effect or if it fails, try another effect with the ",(0,a.yg)("inlineCode",{parentName:"p"},"orElse")," combinator:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val primaryOrBackupData: ZIO[Any, IOException, Array[Byte]] = \n  openFile("primary.data").orElse(openFile("backup.data"))\n')),(0,a.yg)("h2",{id:"folding"},"Folding"),(0,a.yg)("p",null,"In the Scala standard library, the data types ",(0,a.yg)("inlineCode",{parentName:"p"},"Option")," and ",(0,a.yg)("inlineCode",{parentName:"p"},"Either")," have a ",(0,a.yg)("inlineCode",{parentName:"p"},"fold")," method, which lets you handle both failure and success cases at the same time."),(0,a.yg)("p",null,"In a similar fashion, ",(0,a.yg)("inlineCode",{parentName:"p"},"ZIO")," effects also have several methods that allow you to handle both failure and success at the same time."),(0,a.yg)("p",null,"The first fold method, ",(0,a.yg)("inlineCode",{parentName:"p"},"fold"),", lets you separately convert both failure and success into some common type:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'lazy val DefaultData: Array[Byte] = Array(0, 0)\n\nval primaryOrDefaultData: ZIO[Any, Nothing, Array[Byte]] = \n  openFile("primary.data").fold(\n    _    => DefaultData, // Failure case\n    data => data)        // Success case\n')),(0,a.yg)("p",null,"The second fold method, ",(0,a.yg)("inlineCode",{parentName:"p"},"foldZIO"),", lets you separately handle both failure and success by specifying effects that will be executed in each respective case:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val primaryOrSecondaryData: ZIO[Any, IOException, Array[Byte]] = \n  openFile("primary.data").foldZIO(\n    _    => openFile("secondary.data"), // Error handler\n    data => ZIO.succeed(data))          // Success handler\n')),(0,a.yg)("p",null,"The ",(0,a.yg)("inlineCode",{parentName:"p"},"foldZIO")," method is almost the most powerful error recovery method in ZIO, with only ",(0,a.yg)("inlineCode",{parentName:"p"},"foldCauseZIO")," being more powerful. Most other operators, such as ",(0,a.yg)("inlineCode",{parentName:"p"},"either")," or ",(0,a.yg)("inlineCode",{parentName:"p"},"orElse"),", are implemented in terms of these powerful methods."),(0,a.yg)("p",null,"In the following additional example, ",(0,a.yg)("inlineCode",{parentName:"p"},"foldZIO")," is used to handle both the failure and the success of the ",(0,a.yg)("inlineCode",{parentName:"p"},"readUrls")," method:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val urls: ZIO[Any, Nothing, Content] =\n  readUrls("urls.json").foldZIO(\n    error   => ZIO.succeed(Content.NoContent(error)), \n    success => fetchContent(success)\n  )\n')),(0,a.yg)("h2",{id:"retrying"},"Retrying"),(0,a.yg)("p",null,"In order to deal with transient errors, which are the norm when interacting with external cloud systems, ZIO provides very powerful retry mechanisms."),(0,a.yg)("p",null,"One of these mechanisms is the ",(0,a.yg)("inlineCode",{parentName:"p"},"ZIO#retry")," method, which takes a ",(0,a.yg)("inlineCode",{parentName:"p"},"Schedule"),", and returns a new effect that will retry the original effect if it fails, according to the specified schedule:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val retriedOpenFile: ZIO[Any, IOException, Array[Byte]] = \n  openFile("primary.data")\n      .retry(Schedule.recurs(5))\n')),(0,a.yg)("p",null,"The next most powerful function is ",(0,a.yg)("inlineCode",{parentName:"p"},"ZIO#retryOrElse"),", which allows specification of a fallback to use if the effect does not succeed with the specified policy:"),(0,a.yg)("pre",null,(0,a.yg)("code",{parentName:"pre",className:"language-scala"},'val retryOpenFile: ZIO[Any, IOException, DefaultData) = \n  openFile("primary.data")\n      .retryOrElse(Schedule.recurs(5), (_, _) => ZIO.succeed(DefaultData))\n')),(0,a.yg)("p",null,"For more information on how to build schedules, see the documentation on ",(0,a.yg)("a",{parentName:"p",href:"/reference/schedule/"},"Schedule"),"."),(0,a.yg)("h2",{id:"next-steps"},"Next Steps"),(0,a.yg)("p",null,"If you are comfortable with basic error handling, including applying simple retry logic to effects, the next step is to learn about safe ",(0,a.yg)("a",{parentName:"p",href:"/overview/handling-resources"},"resource handling"),"."))}u.isMDXComponent=!0}}]);